[workspace]
members = [
    "libraries/types",
    "storage/photo_storage",
    "test",
    "feed/feed",
    "feed/root_feed",
    "bucket/bucket",
    "bucket/root_bucket",
    "fetch/post_fetch",
    "fetch/root_fetch",
    "user",
    "data_analysis"
]
resolver = "2"
